services:
  activationbase:
    image: activationbase_highvaluecustomer
    container_name: activationbase_highvaluecustomer
    volumes:
      - ai_system_activation:/tmp
    stdin_open: true
    tty: true

volumes:
  ai_system_activation:
    external: true
    name: ai_system_activation